const defaults = {
     realm: "realm",
     updateMillis:100,
     scenenameParam:"render",
     userParam:"X",
     startCoords:"0,1.6,0",
     themeParam:"starry",
     weatherParam:"none",
     mqttParamZ:"127.0.0.1",
     screenSharePath:"screenshare",
     fixedCamera:"",
     ATLASurl:"//atlas.conix.io",
     screenSharePath:"screenshare",
     vioTopic:"/topic/vio/",
     graphTopic:"$NETWORK/latency",
     mqttPath:["/mqtt/"],
     persistHost:"127.0.0.1",
     persistPath:"/persist/",
     urlMqttAuth:"https://127.0.0.1/user/mqtt_auth",
     gAuthClientId:'173603117246-7lehsb3tpq4i17e7sla5bue1an4ps9t6.apps.googleusercontent.com'
};
