const defaults = {
     updateMillis:100,
     scenenameParam:"render",
     userParam:"X",
     startCoords:"0,1.6,0",
     themeParam:"starry",
     weatherParam:"none",
     mqttParamZ:"oz.andrew.cmu.edu",
     fixedCamera:"",
     ATLASurl:"//atlas.conix.io",
     localvidboxWidth:320,
     localvidboxHeight:240,
     vioTopic:"/topic/vio/",
     graphTopic:"$NETWORK/latency",
     mqqtPath:"/xmqtt/",
     persistPath:"/persist/",
     urlMqttAuth:"https://xr.andrew.cmu.edu:8888",
     gAuthClientId:'58999217485-jjkjk88jcl2gfdr45p31p9imbl1uv1iq.apps.googleusercontent.com'
};
