name: ARENA Main SSH Deploy
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: ssh deploy
        #if: endsWith( github.ref, 'deploy') # run for branches or tags ending with 'deploy'
        uses: appleboy/ssh-action@master
        env:
          TARGET: ${{ secrets.ARENA_MAIN_DEPLOY_TARGET }}
        with:
          host: ${{ secrets.ARENA_MAIN_DEPLOY_HOST }}
          username: ${{ secrets.ARENA_MAIN_DEPLOY_USER }}
          key: ${{ secrets.ARENA_MAIN_DEPLOY_KEY }}
          port: ${{ secrets.DEPLOY_PORT }}
          envs: TARGET
          script: |
             cd  $TARGET
             git checkout master
             git reset --hard HEAD
             git pull
             npm ci
             npm run build
             cd ../ARENA-website
             git checkout main
             git reset --hard HEAD
             git pull
             cd ..           
             cp -R ./ARENA-website/* ./ARENA-core/
             ./prod.sh down
             ./prod.sh up --force-recreate -d 

