on:
  push:
    branches:
      - master

permissions:
  contents: write
  issues: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@d1a8f221d7723166f48a584aebba00ef3f6febec # v4.1.4
        with:
          release-type: node
          token: ${{ secrets.RELEASE_PLEASE_PAT }}
